### PR TITLE
Changed url to HTTPS

### PR DESCRIPTION
**Pull request by d4m**
Site enforce redirect to HTTPS. Checking if the user is logged in stopped working.

### CODE REVIEW

**Comment by CaTzil** [comment]
Looks great! Thank you.

Did you managed to check if those changes solves the problem?

**Comment by d4m** [comment]
Yes, I checked this before create PR.

**Comment by CaTzil** [comment]
Cool, publishing it. 
Thank you

**Comment by CaTzil** [comment]
https://github.com/xbmc/repo-scripts/pull/909

**Pull request merged**
